/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZSlideMenus: typeof import('./src/components/z-slide-menus/index.vue')['default']
    ZSlideTabs: typeof import('./src/components/z-slide-tabs/index.vue')['default']
    ZTheme: typeof import('./src/components/z-theme/index.vue')['default']
  }
}
