<template>
  <svg
    width="30"
    height="30"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="17"
      y="6"
      width="14"
      height="9"
      fill="none"
      stroke="#066fe4"
      stroke-width="3"
      stroke-linejoin="miter"
    />
    <rect
      x="6"
      y="33"
      width="14"
      height="9"
      fill="none"
      stroke="#066fe4"
      stroke-width="3"
      stroke-linejoin="miter"
    />
    <rect
      x="28"
      y="33"
      width="14"
      height="9"
      fill="none"
      stroke="#066fe4"
      stroke-width="3"
      stroke-linejoin="miter"
    />
    <path
      d="M24 16V24"
      stroke="#066fe4"
      stroke-width="3"
      stroke-linecap="butt"
      stroke-linejoin="miter"
    />
    <path
      d="M13 33V24H35V33"
      stroke="#066fe4"
      stroke-width="3"
      stroke-linecap="butt"
      stroke-linejoin="miter"
    />
  </svg>
</template>
<script setup lang="ts">
defineOptions({
  name: "MenuGraph",
});
</script>
